### ISSUE TITLE
Unzipping dataset asking for password

### ISSUE THREAD

**Issue by hritik5102** [omar-sharif03/CONSTRAINT-AAAI2021#2]
@omar-sharif03 what is the password ?, I'll want to use this dataset for my research work, can you help with that.
Thank you :)

**Comment by omar-sharif03** [comment]
Organizers have publicly released the dataset. Check the link

[https://competitions.codalab.org/competitions/26654#learn_the_details-dataset](url)

**Comment by omar-sharif03** [comment]
Organizers have released the dataset publicly. Check the link

[https://competitions.codalab.org/competitions/26654#learn_the_details-dataset](https://competitions.codalab.org/competitions/26654#learn_the_details-dataset)

**Comment by hritik5102** [comment]
But I want an English dataset, not for Hindi.
I'm talking about this one: [Constraint@AAAI2021 - COVID19 Fake News Detection in English](https://competitions.codalab.org/competitions/26655)

So to disturb you, if possible can you share your password, or else can you share the dataset of the above link

**Comment by omar-sharif03** [comment]
I have removed the password. Please check.

**Comment by hritik5102** [comment]
Yes, got it. thank you :)
I'm closing this issue.
