### ISSUE TITLE
Code Description

### ISSUE THREAD

**Issue by EngineerSE** [omar-sharif03/CONSTRAINT-AAAI2021#3]
@eftekhar-hossain  @omar-sharif03  
In your paper, it is mentioned that these classifiers are used for task A
CNN + BiLSTM 
SVM + TF-idf 
SVM + Word2Vec (ED=200) 
SVM + Word2Vec (ED=150)

In the code folder, there are three files related to Task A.  Can you explain which file contains which classifier from the above mentioned 4 classifiers?

**Comment by omar-sharif03** [comment]
1st file: examined statistics of data, implement deep learning models (CNN, BiLSTM, CNN+BiLSTM)
2nd file: implemented SVM model with tf-idf
3rd file: tried to use pre-trained word vectors with DL methods. (might have some inconsistencies)

We have implemented multiple models in single files. Feel free to run the code and change where needed.

**Comment by EngineerSE** [comment]
@omar-sharif03  By the first file, you mean this Constraint_AAAI2021_(English_Fake_News).ipynb file, second is Constraint_Fake_News_(Try_2)(SVM)) and third is Constraint_Fake_News_(Try_3)))?

**Comment by omar-sharif03** [comment]
Yes

**Comment by EngineerSE** [comment]
okay thank you
